export default [
  {
    name: "Unemployed",
    value: 8,
    icon: "",
    desc: "8 free trait points.",
  },
  {
    name: "Fire Officer",
    value: 0,
    icon: "/occupations/fireofficer.png",
    desc: "+1 Axe. +1 Fitness. +1 Sprinting. +1 Strength",
  },
  {
    name: "Police Officer",
    value: -4,
    icon: "/occupations/policeofficer.png",
    desc: "+3 Aiming. +1 Nimble. +2 Reloading.",
  },
  {
    name: "Park Ranger",
    value: -4,
    icon: "/occupations/parkranger.png",
    desc: "Allows much faster movement through forests and woodland. +1 Axe. +1 Carpentry. +2 Foraging. +2 Trapping.",
  },
  {
    name: "Construction Worker",
    value: -2,
    icon: "/occupations/constructionworker.png",
    desc: "+1 Carpentry. +3 Short Blunt.",
  },
  {
    name: "Security Guard",
    value: -2,
    icon: "/occupations/securityguard.png",
    desc: "+1 Lightfooted. +2 Sprinting. Night Owl.",
  },
  {
    name: "Carpenter",
    value: 2,
    icon: "/occupations/carpenter.png",
    desc: "+3 Carpentry. +1 Short Blunt.",
  },
  {
    name: "Burglar",
    value: -6,
    icon: "/occupations/burglar.png",
    desc: "Can hotwire vehicles. Less chance of breaking the lock of a window. +2 Lightfooted. +2 Nimble. +2 Sneaking. Burglar",
  },
  {
    name: "Chef",
    value: -4,
    icon: "/occupations/chef.png",
    desc: "+3 Cooking. +1 Maintenance. +1 Short Blade. Cook.",
  },
  {
    name: "Repairman",
    value: -4,
    icon: "/occupations/repairman.png",
    desc: "+1 Carpentry. +2 Maintenance. +1 Short Blunt.",
  },
  {
    name: "Farmer",
    value: 2,
    icon: "/occupations/farmer.png",
    desc: "+3 Farming.",
  },
  {
    name: "Fisherman",
    value: -2,
    icon: "/occupations/fisherman.png",
    desc: "+3 Fishing. +1 Foraging.",
  },
  {
    name: "Doctor",
    value: 2,
    icon: "/occupations/doctor.png",
    desc: "+3 First Aid. +1 Short Blade.",
  },
  {
    name: "Veteran",
    value: -8,
    icon: "/occupations/veteran.png",
    desc: "+2 Aiming. +2 Reloading. Desensitized.",
  },
  {
    name: "Nurse",
    value: 2,
    icon: "/occupations/nurse.png",
    desc: "+2 First aid. +1 Lightfooted.",
  },
  {
    name: "Lumberjack",
    value: 0,
    icon: "/occupations/lumberjack.png",
    desc: "Allows slightly faster movement through forests and woodland. +2 Axe. +1 Strength. Axe Man.",
  },
  {
    name: "Fitness Instructor",
    value: -6,
    icon: "/occupations/fitnessinstructor.png",
    desc: "+3 Fitness. +2 Sprinting. Nutritionist.",
  },
  {
    name: "Burger Flipper",
    value: 2,
    icon: "/occupations/burgerflipper.png",
    desc: "+2 Cooking. +1 Maintenance. +1 Short Blade. Cook.",
  },
  {
    name: "Electrician",
    value: -4,
    icon: "/occupations/electrician.png",
    desc: "Can operate generators. +3 Electrical.",
  },
  {
    name: "Engineer",
    value: -4,
    icon: "/occupations/engineer.png",
    desc: "Can make traps and explosives. +1 Carpentry. +1 Electrical.",
  },
  {
    name: "Metalworker",
    value: -6,
    icon: "/occupations/metalworker.png",
    desc: "Can weld foraged metal to create items and barricades. +3 Metalworking.",
  },
  {
    name: "Mechanic",
    value: -4,
    icon: "/occupations/mechanic.png",
    desc: "+3 Mechanics. +1 Short Blunt. Amateur Mechanic.",
  },
];
